apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: service
    app.kubernetes.io/instance: webhook-service
    app.kubernetes.io/component: webhook
    app.kubernetes.io/created-by: multicloud-mongo-operator
    app.kubernetes.io/part-of: multicloud-mongo-operator
    app.kubernetes.io/managed-by: kustomize
  name: federation-mongo-manager-service
  namespace: federation-mongo-operator
spec:
  externalName: federation-mongo-manager-service.federation-mongo-operator.svc.cluster.local
  type: ExternalName