---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: federation-mongo-operator-mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURmRENDQW1TZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREJMTVNJd0lBWURWUVFLRXhsbVpXUmwKY21GMGFXOXVMVzF2Ym1kdkxXOXdaWEpoZEc5eU1TVXdJd1lEVlFRREV4eG1aV1JsY21GMGFXOXVMVzF2Ym1kdgpMVzl3WlhKaGRHOXlMV05oTUI0WERUSXpNRE13T0RBM01UQXpNVm9YRFRNek1ETXdOVEE0TVRBek1Wb3dTekVpCk1DQUdBMVVFQ2hNWlptVmtaWEpoZEdsdmJpMXRiMjVuYnkxdmNHVnlZWFJ2Y2pFbE1DTUdBMVVFQXhNY1ptVmsKWlhKaGRHbHZiaTF0YjI1bmJ5MXZjR1Z5WVhSdmNpMWpZVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUApBRENDQVFvQ2dnRUJBS01MTkZ0T1M2WkcxT25UNkpkTmF0NWl3cWxVNnpLU01VOTJ0b0hpZ3pNb0dxMkFhaVQ3CkxXYjBSTSttVTlXcCtYbTZ5MVlqWXdNUFkxcERjd2ppSWd0YjVqaGM4c29TY3l6b0c5ZVBjRUg0eUJVeGlkRmUKaDhRQlpPdU9yNnFxSnpnbC9SR3I1M3NiSDUwaVFLK0ZmdUZBM0RQNlVSZDg5TkdPOTdpRkZOa2IvRmRYdndyOQoxNFV4a3FvSTVQV3ROTTZteC9ib2hPODROMkZSRUh4MW9LS3pUeUg0SjdncWV4OEs5UVhaOUhVQ0FUdVRRbkFZCmZZTXhEMitWTUg5cm5qWm9weXZlTkxyQUVzWGlxQ3NQYWhYZmwzdXZWWnJKVEJ6T3FiUG1xTEJsZDBJS1l6S2sKUkhibk9vbk1aakl1TTRyak5HcXA4MDhRaHc0UEFNT3BnU0VDQXdFQUFhTnJNR2t3RGdZRFZSMFBBUUgvQkFRRApBZ0trTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRkVWRHpGK21TMFB5QWtYUEdBK285SUJ0CmJ2Y1JNQ2NHQTFVZEVRUWdNQjZDSEdabFpHVnlZWFJwYjI0dGJXOXVaMjh0YjNCbGNtRjBiM0l0WTJFd0RRWUoKS29aSWh2Y05BUUVMQlFBRGdnRUJBQVQ1M1JKUlVwNDNnSGZlRko2aXk2VDFMc2ErK2p0U2pFcG0wbC9pMGVmTwo1cnRNelRMV3hLK25BYTNhNjlQMUU4V0orZWxiNUt6WktET1djSHgxVm1aZEZuUkJ1ZHd6TGxBV21EZEZJVmV4CkpwSmdFMmRoMmVKdkNURitQU1FNV3pVNmtCZ1ZDVlhtRTZyb3hyTWg3TnRDOVp2REl4TGVFSlZyMjNMVW5ZMS8KaXNYV3hNNncya1lyUW5MQU9EM1g4bzB3cnl3ZHFDSzBHSGcxUnZqa0lwd21JZFFaZFlOb1MyL1A2MzFLcngxVQp3Vjg4Mi9QcGhXOEhOQ24yOGVPRzg1Q3RVVlVITEVBVXJ2OTZQZE10dGMwVmtnak5pdHFXUk91V1loT1FjYnNwCkpsME5EN0FvUEtPczQyZlYvSFZIZEYxNmVNSG5IWDhocTY3SWZobkhodFU9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    service:
      name: federation-mongo-manager-service
      namespace: federation-mongo-operator
      path: /mutate-middleware-fedstate-io-v1alpha1-multicloudmongodb
  failurePolicy: Fail
  name: mmulticloudmongodb.kb.io
  rules:
  - apiGroups:
    - middleware.fedstate.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - multicloudmongodbs
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: federation-mongo-operator-validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURmRENDQW1TZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREJMTVNJd0lBWURWUVFLRXhsbVpXUmwKY21GMGFXOXVMVzF2Ym1kdkxXOXdaWEpoZEc5eU1TVXdJd1lEVlFRREV4eG1aV1JsY21GMGFXOXVMVzF2Ym1kdgpMVzl3WlhKaGRHOXlMV05oTUI0WERUSXpNRE13T0RBM01UQXpNVm9YRFRNek1ETXdOVEE0TVRBek1Wb3dTekVpCk1DQUdBMVVFQ2hNWlptVmtaWEpoZEdsdmJpMXRiMjVuYnkxdmNHVnlZWFJ2Y2pFbE1DTUdBMVVFQXhNY1ptVmsKWlhKaGRHbHZiaTF0YjI1bmJ5MXZjR1Z5WVhSdmNpMWpZVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUApBRENDQVFvQ2dnRUJBS01MTkZ0T1M2WkcxT25UNkpkTmF0NWl3cWxVNnpLU01VOTJ0b0hpZ3pNb0dxMkFhaVQ3CkxXYjBSTSttVTlXcCtYbTZ5MVlqWXdNUFkxcERjd2ppSWd0YjVqaGM4c29TY3l6b0c5ZVBjRUg0eUJVeGlkRmUKaDhRQlpPdU9yNnFxSnpnbC9SR3I1M3NiSDUwaVFLK0ZmdUZBM0RQNlVSZDg5TkdPOTdpRkZOa2IvRmRYdndyOQoxNFV4a3FvSTVQV3ROTTZteC9ib2hPODROMkZSRUh4MW9LS3pUeUg0SjdncWV4OEs5UVhaOUhVQ0FUdVRRbkFZCmZZTXhEMitWTUg5cm5qWm9weXZlTkxyQUVzWGlxQ3NQYWhYZmwzdXZWWnJKVEJ6T3FiUG1xTEJsZDBJS1l6S2sKUkhibk9vbk1aakl1TTRyak5HcXA4MDhRaHc0UEFNT3BnU0VDQXdFQUFhTnJNR2t3RGdZRFZSMFBBUUgvQkFRRApBZ0trTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRkVWRHpGK21TMFB5QWtYUEdBK285SUJ0CmJ2Y1JNQ2NHQTFVZEVRUWdNQjZDSEdabFpHVnlZWFJwYjI0dGJXOXVaMjh0YjNCbGNtRjBiM0l0WTJFd0RRWUoKS29aSWh2Y05BUUVMQlFBRGdnRUJBQVQ1M1JKUlVwNDNnSGZlRko2aXk2VDFMc2ErK2p0U2pFcG0wbC9pMGVmTwo1cnRNelRMV3hLK25BYTNhNjlQMUU4V0orZWxiNUt6WktET1djSHgxVm1aZEZuUkJ1ZHd6TGxBV21EZEZJVmV4CkpwSmdFMmRoMmVKdkNURitQU1FNV3pVNmtCZ1ZDVlhtRTZyb3hyTWg3TnRDOVp2REl4TGVFSlZyMjNMVW5ZMS8KaXNYV3hNNncya1lyUW5MQU9EM1g4bzB3cnl3ZHFDSzBHSGcxUnZqa0lwd21JZFFaZFlOb1MyL1A2MzFLcngxVQp3Vjg4Mi9QcGhXOEhOQ24yOGVPRzg1Q3RVVlVITEVBVXJ2OTZQZE10dGMwVmtnak5pdHFXUk91V1loT1FjYnNwCkpsME5EN0FvUEtPczQyZlYvSFZIZEYxNmVNSG5IWDhocTY3SWZobkhodFU9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    service:
      name: federation-mongo-manager-service
      namespace: federation-mongo-operator
      path: /validate-middleware-fedstate-io-v1alpha1-multicloudmongodb
  failurePolicy: Fail
  name: vmulticloudmongodb.kb.io
  rules:
  - apiGroups:
    - middleware.fedstate.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - multicloudmongodbs
  sideEffects: None
