---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-middleware-daocloud-io-v1alpha1-mongodb
  failurePolicy: Fail
  name: mmongodb.kb.io
  rules:
  - apiGroups:
    - middleware.daocloud.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - mongodbs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-middleware-daocloud-io-v1alpha1-multicloudmongodb
  failurePolicy: Fail
  name: mmulticloudmongodb.kb.io
  rules:
  - apiGroups:
    - middleware.daocloud.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - multicloudmongodbs
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-middleware-daocloud-io-v1alpha1-mongodb
  failurePolicy: Fail
  name: vmongodb.kb.io
  rules:
  - apiGroups:
    - middleware.daocloud.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - mongodbs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-middleware-daocloud-io-v1alpha1-multicloudmongodb
  failurePolicy: Fail
  name: vmulticloudmongodb.kb.io
  rules:
  - apiGroups:
    - middleware.daocloud.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - multicloudmongodbs
  sideEffects: None
