apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: service
    app.kubernetes.io/instance: mongo-manager
    app.kubernetes.io/component: webhook
    app.kubernetes.io/created-by: multicloud-mongo-operator
    app.kubernetes.io/part-of: multicloud-mongo-operator
    app.kubernetes.io/managed-by: kustomize
  name: mongo-manager
  namespace: mongo-operator
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    control-plane: multicloud-mongo-operator
