apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: multicloud-mongo-operator
    app.kubernetes.io/part-of: multicloud-mongo-operator
    app.kubernetes.io/managed-by: kustomize
  name: federation-mongo-manager-sa
  namespace: federation-mongo-operator
