apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/instance: mongo-manager-rolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: multicloud-mongo-operator
    app.kubernetes.io/part-of: multicloud-mongo-operator
    app.kubernetes.io/managed-by: kustomize
  name: mongo-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mongo-operator-cluster-role
subjects:
- kind: ServiceAccount
  name: mongo-manager-sa
  namespace: mongo-operator
